// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPM7fw1naJs9w4wEbKPaZ3oUW7KZ_2D3E',
    appId: '1:365895674605:web:b99164b502a4019144bae4',
    messagingSenderId: '365895674605',
    projectId: 'auth-2a350',
    authDomain: 'auth-2a350.firebaseapp.com',
    storageBucket: 'auth-2a350.appspot.com',
    measurementId: 'G-PZFSDGEK43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3fExiCMAJndeenDj_vvTjsflFWMCpi8M',
    appId: '1:365895674605:android:b71b370c3238772044bae4',
    messagingSenderId: '365895674605',
    projectId: 'auth-2a350',
    storageBucket: 'auth-2a350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMX4ghgSQPWaZL88Hq3nug0q9Oad5yLLY',
    appId: '1:365895674605:ios:d4d50a576fad115744bae4',
    messagingSenderId: '365895674605',
    projectId: 'auth-2a350',
    storageBucket: 'auth-2a350.appspot.com',
    androidClientId: '365895674605-gpn4rfa87920hil41j3ld0k9eirvb07l.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMX4ghgSQPWaZL88Hq3nug0q9Oad5yLLY',
    appId: '1:365895674605:ios:2d2ba936c38637f244bae4',
    messagingSenderId: '365895674605',
    projectId: 'auth-2a350',
    storageBucket: 'auth-2a350.appspot.com',
    androidClientId: '365895674605-gpn4rfa87920hil41j3ld0k9eirvb07l.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
